### PR TITLE
Allow uploading files even when permissions cannot be set.

### PR DESCRIPTION
**Pull request by alexeyklyukin**
By default, the "file" function uses sftp to upload the target file to
the server. During the upload, the Net::SFTP::Foreign runs chmod
unconditionally, failing if the target file is not owned by the ssh
user, unless that user is a root. This commit changes that behavior by
passing an optional "best_effort" flag that instructs sftp to continue
even if setting permissions has failed.

As a result, an unprivileged user will be able to use Rex scenarios that
call the "file" function without getting permission denied errors.

### CODE REVIEW

**Review by einhverfr — CHANGES_REQUESTED** [review]
After discussions, we are concerned about this as a global change.  Could we change this to either accept a argument from the File interface all the way down or use an environment variable?

**Review by einhverfr — APPROVED** [review]
Now this looks ok to me.  want another review though.

**Comment by alexeyklyukin** [comment]
LGTM

**Comment by alexeyklyukin** [comment]
Thank you!

**Pull request merged**
